#!/usr/bin/env python3

from main import main, get_parser

if __name__ == '__main__':

    args = get_parser().parse_args()

    main(
        fasta_file = args.fasta,
        bigwig_file = args.bigwig,
        ori_file = args.ori,
        outprefix = args.outprefix,
        window_size = args.window_size,
    )