use-conda: True
keep-going: True
rerun-incomplete: True
jobs : 100
cores : 100
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
use-conda: True
use-singularity: False
jobs: 100
printshellcmds: True
restart-times: 2
default-resources: [mem_mb=2048, runtime="10m"]