#!/bin/bash

bam_in=$1
contigs=$2
sam_out=$3

if [ -z "$bam_in" ] || [ -z "$contigs" ] || [ -z "$sam_out" ]; then
    echo "Usage: $0 bam-in contigs sam-out stats-out"
    exit 1
fi

# copy header over to new sam file
#samtools view -H $bam_in > $sam_out

# filter out unmapped reads, reads with no probability of alignment,
# and supplementary reads, then filter for properly-mapped pairs
# and get just the read 1's.
# Sort the bam by name, then extract the reads for which there are
# multiple mappings (duplicates on name field).
samtools view -q 0 -F -0x800 -F 0x400 -F 0x4 -f 0x2 -f 0x1 -f 0x40 -h $bam_in \
    | samtools sort -n -O sam -T $TMPDIR | awk '{
        if ($0 ~ /^@/) {
            print;
        } else {
            if ($1 in count) {
                if (count[$1] == 1) {
                    print seen[$1];
                    count[$1]++;
                }
                print;
            } else {
                seen[$1] = $0;
                count[$1] = 1;
            }
        } 
    }' > $sam_out
